// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmwcv0PVPlLwkJxA5MxlPUuatNCtkbIhI',
    appId: '1:699322756942:web:ede5f2cc4c1ed876a8f81f',
    messagingSenderId: '699322756942',
    projectId: 'pemrograman-mobile-ii',
    authDomain: 'pemrograman-mobile-ii.firebaseapp.com',
    storageBucket: 'pemrograman-mobile-ii.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxZ1uph571hfgr7gOB3h2138qkpLJF87g',
    appId: '1:699322756942:android:8810c3a34148e9bba8f81f',
    messagingSenderId: '699322756942',
    projectId: 'pemrograman-mobile-ii',
    storageBucket: 'pemrograman-mobile-ii.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4kY4DvdguHLp3UWL23A_GsFjfFdAd3kA',
    appId: '1:699322756942:ios:1beaa8f673459edea8f81f',
    messagingSenderId: '699322756942',
    projectId: 'pemrograman-mobile-ii',
    storageBucket: 'pemrograman-mobile-ii.appspot.com',
    iosBundleId: 'com.patamorgana.flutterCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4kY4DvdguHLp3UWL23A_GsFjfFdAd3kA',
    appId: '1:699322756942:ios:1beaa8f673459edea8f81f',
    messagingSenderId: '699322756942',
    projectId: 'pemrograman-mobile-ii',
    storageBucket: 'pemrograman-mobile-ii.appspot.com',
    iosBundleId: 'com.patamorgana.flutterCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmwcv0PVPlLwkJxA5MxlPUuatNCtkbIhI',
    appId: '1:699322756942:web:9ab617abb6c485d7a8f81f',
    messagingSenderId: '699322756942',
    projectId: 'pemrograman-mobile-ii',
    authDomain: 'pemrograman-mobile-ii.firebaseapp.com',
    storageBucket: 'pemrograman-mobile-ii.appspot.com',
  );
}
